# Generated by Django 4.1.1 on 2022-10-06 10:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0004_remove_clientevents_date_remove_clientevents_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientevents',
            name='anniversary',
        ),
        migrations.RemoveField(
            model_name='clientevents',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='clientevents',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 6, 10, 33, 57, 165955, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientevents',
            name='name',
            field=models.CharField(default='kunal', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientphone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
