# Generated by Django 4.1.1 on 2022-10-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_remove_clientevents_anniversary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
