# Generated by Django 4.1.1 on 2022-10-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
