# Generated by Django 4.1.1 on 2022-10-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_clientphone_clientevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientphone',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientEvents',
        ),
        migrations.DeleteModel(
            name='ClientPhone',
        ),
    ]
