# Generated by Django 4.1.1 on 2022-10-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0004_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="keyword",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="select_before_date",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="select_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="select_tags",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
