# Generated by Django 4.1.1 on 2022-10-06 08:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0005_alter_trigger_keyword_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 6, 13, 44, 4, 819252)
            ),
        ),
    ]
