# Generated by Django 4.1.1 on 2022-10-06 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_alter_campaign_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 14, 39, 40, 729537)),
        ),
    ]
