# Generated by Django 4.1.1 on 2022-10-06 10:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0007_trigger_phone_alter_campaign_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 6, 15, 37, 40, 984708)
            ),
        ),
    ]
