# Generated by Django 4.1.1 on 2022-10-07 05:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0014_alter_campaign_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 7, 10, 30, 6, 239007)
            ),
        ),
    ]
