# Generated by Django 4.1.1 on 2022-10-07 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_rename_tags_tag'),
        ('campaign', '0015_alter_campaign_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 11, 35, 34, 746398)),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='select_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.clientevents'),
        ),
    ]
