# Generated by Django 4.1.1 on 2022-10-07 06:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0017_alter_campaign_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 7, 11, 36, 52, 715188)
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="select_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
