# Generated by Django 4.1.1 on 2022-10-07 06:07

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0007_rename_tags_tag"),
        ("campaign", "0019_alter_campaign_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 7, 11, 37, 52, 420791)
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="select_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Client.clientevents",
            ),
        ),
    ]
