# Generated by Django 4.1.1 on 2022-10-07 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_alter_campaign_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 11, 45, 56, 562266)),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
