# Generated by Django 4.1.1 on 2022-10-07 07:14

import datetime

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0007_rename_tags_tag"),
        ("campaign", "0021_alter_campaign_date_created_alter_trigger_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="cancellation_trigger",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="double_optin",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="double_optin_keyword",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="double_optin_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="limit_multiple",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="limit_multiple_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="on_reply",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="send_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Client.clientphone",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="sending_window",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="sent_days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Mon", "Mon"),
                    ("Tues", "Tues"),
                    ("Wens", "Wens"),
                    ("Thurs", "Thurs"),
                    ("Fri", "Fri"),
                    ("Sat", "Sat"),
                    ("Sun", "Sun"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 7, 12, 44, 36, 241373)
            ),
        ),
    ]
