# Generated by Django 4.1.1 on 2022-10-07 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0022_campaign_cancellation_trigger_campaign_double_optin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cancellation_trigger',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 12, 52, 25, 514029)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='double_optin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='limit_multiple',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
