# Generated by Django 4.1.1 on 2022-10-07 07:48

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0007_rename_tags_tag"),
        ("campaign", "0023_alter_campaign_cancellation_trigger_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 7, 13, 18, 40, 598876)
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="phone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Client.clientphone",
            ),
        ),
    ]
