# Generated by Django 4.1.1 on 2022-10-07 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0025_alter_campaign_date_created_alter_trigger_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 13, 19, 25, 927954)),
        ),
    ]
