# Generated by Django 4.1.1 on 2022-10-07 08:56

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0035_alter_campaign_date_created_alter_campaign_sent_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 14, 26, 28, 873114)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sent_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Mon'), ('Tues', 'Tues'), ('Wens', 'Wens'), ('Thurs', 'Thurs'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=100, null=True),
        ),
    ]
