# Generated by Django 4.1.1 on 2022-10-11 06:19

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0008_time"),
        ("campaign", "0038_alter_campaign_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 11, 11, 49, 21, 858739)
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="end_time",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_time",
                to="Client.time",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_time",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_time",
                to="Client.time",
            ),
            preserve_default=False,
        ),
    ]
