# Generated by Django 4.1.1 on 2022-10-11 09:44

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0008_time"),
        (
            "campaign",
            "0039_alter_campaign_date_created_alter_campaign_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 11, 15, 14, 45, 867028)
            ),
        ),
        migrations.CreateModel(
            name="Actions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_message",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minutes", "minutes"),
                            ("hours", "hours"),
                            ("days", "days"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("wait_until", models.TimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.campaign",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Client.tag",
                    ),
                ),
            ],
        ),
    ]
