# Generated by Django 4.1.1 on 2022-10-11 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_time'),
        ('campaign', '0040_alter_campaign_date_created_actions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Action',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 16, 54, 290704)),
        ),
    ]
