# Generated by Django 4.1.1 on 2022-10-11 11:12

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0043_alter_campaign_date_created_alter_trigger_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="campaign.campaign"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 11, 16, 42, 35, 220909)
            ),
        ),
    ]
