# Generated by Django 4.1.1 on 2022-10-11 12:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0044_alter_action_campaign_alter_campaign_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 11, 18, 19, 2, 82050)
            ),
        ),
    ]
