# Generated by Django 4.1.1 on 2022-10-14 07:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0045_alter_action_number_alter_campaign_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 14, 13, 20, 51, 132967)
            ),
        ),
    ]
