# Generated by Django 4.1.1 on 2022-10-14 07:51

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0046_alter_campaign_date_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="action",
            name="number",
        ),
        migrations.RemoveField(
            model_name="action",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="action",
            name="text_message",
        ),
        migrations.RemoveField(
            model_name="action",
            name="wait_until",
        ),
        migrations.AddField(
            model_name="action",
            name="action",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 14, 13, 21, 19, 828895)
            ),
        ),
    ]
