# Generated by Django 4.1.1 on 2022-10-14 07:52

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0047_remove_action_duration_remove_action_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 14, 13, 22, 42, 668011)
            ),
        ),
    ]
