# Generated by Django 4.1.1 on 2022-10-14 07:52

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0048_action_order_alter_campaign_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 14, 13, 22, 53, 722534)
            ),
        ),
    ]
