# Generated by Django 4.1.1 on 2022-10-16 12:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0050_alter_campaign_date_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="type",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 16, 17, 37, 47, 318942)
            ),
        ),
    ]
