# Generated by Django 4.1.1 on 2022-10-17 06:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0055_remove_action_action_remove_action_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 17, 11, 33, 21, 511899)
            ),
        ),
    ]
