# Generated by Django 4.1.1 on 2022-10-17 06:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0056_alter_campaign_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 17, 12, 28, 39, 312744)
            ),
        ),
    ]
