# Generated by Django 4.1.1 on 2022-10-17 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0057_action_order_alter_campaign_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 12, 30, 11, 430684)),
        ),
    ]
